Webeloperss/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from Webeloperss import settings
from webapp import views

urlpatterns = [
    path('reset/', views.reset),
    path('forgot/', views.forgot),
    path('search_teachers_api/', views.search_teachers),
    path('editprofile/', views.editprofile),
    path('createmeeting/', views.createmeeting),
    path('removeuser/', views.removeuser),
    path('search/', views.search),
    path('profile/', views.profile),
    path('contactus/', views.contactus),
    path('logout/', views.logout_),
    path('login/', views.login_),
    path('signup/', views.signup),
    path('', views.main),
    path('admin/', admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

webapp/models.py
from webbrowser import register

from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    gender = models.CharField(
        max_length=2, choices=(('M', 'مرد'), ('F', 'زن')), default='M'
    )
    picture = models.FileField(blank=True, null=True, upload_to="")


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Meeting(models.Model):
    start = models.DateTimeField()
    end = models.DateTimeField()
    date = models.DateTimeField()
    teacher = models.ForeignKey(User, on_delete=models.CASCADE)
    capacity = models.IntegerField()

    class Meta:
        verbose_name_plural = "Teacher Free Times"

templates/base.html
{% load static %}
<!doctype html>
<html lang="fa" dir="rtl">
<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.css"/>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/components/icon.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/components/icon.min.css">
    <script src="{% static 'jquery.min.js' %}"></script>
    {#    <script src="{%  static 'semantic.min.css' %}"></script>#}
    {##}
    {#    <script src="{%  static 'semantic.min.js' %}"></script>#}
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Ostad Joo</title>
</head>
<body>
<nav id="id_navbar" class="ui inverted menu">
    <a href="/" id="id_navbar_home" class="item">استاد جو</a>
    <div class="left menu">
        <div class="ui right aligned category search item">
            <form action="/search" method="get">
                <input name="search_param" id="id_search_profiles_input" type="text" placeholder="جستجوی اساتید" style="color: black">
                <button class="search link icon" type="submit" id="id_search_profiles_button">search</button>
            </form>
        </div>
        {% if user.is_authenticated %}
            <a href="/profile" id="id_navbar_profile" class="item">نمایه</a>
            <a href="/logout" id="id_navbar_logout" class="item">خروج</a>
            {#             {% if user.is_staff %}#}
            <a href="/createmeeting/" id="id_navbar_meeting" class="item">ساخت فرصت</a>

            {#             {% endif %}#}
        {% else %}
            <a href="/login" id="id_navbar_login" class="item">ورود</a>
        {% endif %}
        <a href="/signup" id="id_navbar_signup" class="item">ثبت نام</a>
        <a href="/contactus" id="id_navbar_contact_us" class="item">تماس با ما</a>
    </div>
</nav>
<div id="main-content" class="ui cented aligned text container" style="padding: 15px;">
    {% block content %}

    {% endblock %}
</div>
</body>
</html>
{% block scripts %}
{% endblock %}

templates/contactus.html
{% extends "base.html" %}
{% block content %}
    <form action="." method="post">
        {% csrf_token %}
        <input type="text" id="id_title" name="title" maxlength="40" required>
        <input type="text" id="id_text" name="text" minlength="10" maxlength="250" required>
        <input type="email" id="id_email" name="email">
        <button type="submit" id="id_submit">submit</button>
    </form>
{% endblock %}
{% block scripts %}
<script>
    $(document).ready(function () {
        $("#id_navbar_contact_us").addClass("active");
    });

</script>
{% endblock %}

templates/createmeeting.html
{% extends "base.html" %}
{% block content %}
    {% if falseDate %}
        <p>تاریخ وارد شده معتبر نمی‌باشد</p>
    {% endif %}
    {% if falseStart %}
        <p>زمان شروع وارد شده معتبر نمی‌باشد</p>
    {% endif %}
    {% if falseEnd %}
        <p>زمان پایان وارد شده معتبر نمی‌باشد</p>
    {% endif %}
    {% if endBeforeStart %}
        <p>زمان شروع باید قبل از زمان پایان فرصت باشد</p>
    {% endif %}
    {% if intersection %}
        <p>بازه زمانی انتخاب شده با فرصت های قبلی شما اشتراک دارد</p>
    {% endif %}
    <form action="." method="post">
        {% csrf_token %}
        <input type="text" placeholder="تاریخ" id="id_date" name="date">
        <input type="text" placeholder="زمان شروع" id="id_start" name="start">
        <input type="text" placeholder="زمان پایان" id="id_end" name="end">
        <input type="number" placeholder="ظرفیت" id="id_student_capacity" name="capacity">
        <button id="id_submit" type="submit">submit</button>
    </form>
{% endblock %}

templates/edit_profile.html
{% extends "base.html" %}
{% block content %}
    <div class="ui middle aligned center aligned grid">
        <div class="column four wide">
            <form id="editform" action="." method="post" enctype="multipart/form-data" class="ui form segment">
                {% csrf_token %}
                <input type="text" id="id_first_name" name="first" placeholder="نام" value="{{ user.first_name }}" required>
                <input type="text" id="id_last_name" name="last" placeholder="نام خانوادگی" value="{{ user.last_name }}" required>

                <select id="id_gender" multiple value="{{ user.profile.gender }}" name="gender" required>
                    {% if user.profile.gender == 'M' %}
                        <option value="M" selected>مرد</option>
                        <option value="F">زن</option>
                    {% else %}
                        <option value="M">مرد</option>
                        <option selected value="F">زن</option>
                    {% endif %}
                </select>
                <br/>
                <input type="file" accept="image/*" value="{{ user.profile.picture }}" name="pic" id="id_picture">
                <button type="submit" id="id_submit">edit</button>
            </form>
            <textarea wrap="soft" form="editform" id="id_bio" value="" name="bio" {{ user.profile.bio }}></textarea>

        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script>
        $(document).ready(function () {
            $("#id_navbar_signup").addClass("active");
        });
        {#$('.ui.checkbox')#}
        {#    .checkbox()#}
        {#;#}
    </script>
{% endblock %}

templates/forgot.html
{% extends "base.html" %}
{% block content %}
    <form  action="." method="post">
        <input name="email" type="email" id="id_email"/>
        <button id="id_submit">submit</button>
    </form>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block content %}


<div class="ui middle aligned center aligned grid" id="greeting">
   <div class="column">
       <p style="font-size: 2.25rem;">سلام. به سامانه استادجو خوش آمدید.</p>
   </div>
</div>

{% endblock %}
{% block scripts %}
<script>
    $(document).ready(function () {
        $("#id_navbar_home").addClass("active");
    });

</script>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block content %}
    <div class="ui middle aligned center aligned grid">
        <div class="column four wide">
            <form action="." method="post" class="ui form segment " dir="ltr">
                {% csrf_token %}
                {% if error %}
                    <p class="ui negative message">نام کاربری یا گذرواژه غلط است</p>
                {% endif %}
                <div class="field">
                    <div class="ui left icon input">
                        <i class="user icon"></i>
                        <input type="text" id="id_username" name="username" placeholder="نام کاربری"/>

                    </div>
                </div>
                <div class="field">
                    <div class="ui left icon input">
                        <i class="lock icon"></i>
                        <input type="password" id="id_password" name="password" placeholder="گذرواژه"/>

                    </div>
                </div>
                <button class="circular ui fade icon button" type="submit" id="id_submit" style="background-color: #3494E6">
                    <i class="icon white key"></i>
                </button>
            </form>
            <a href="/forgot" id="id_forget_password">forgot</a>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script>
        $(document).ready(function () {
            $("#id_navbar_login").addClass("active");
        });

    </script>
{% endblock %}

templates/profile.html
{% extends "base.html" %}
{% block content %}
    <div class="ui middle aligned center aligned divided grid" dir="rtl">
        <div class="column twelve wide">
            <div class="ui segment">
                <h1 class="ui right aligned header">نمایه</h1>
                <a class="ui left aligned column " href="/editprofile" id="id_edit_profile">ویرایش</a>
                <button onclick="remove()" id="id_remove_user">حذف کاربر
                </button>
                <div class="ui divider"></div>
                <div class="ui grid">
                    <div class="column right aligned four wide " dir="rtl">
                        <div class="label-seperator">
                            <label for="id_first_name" class="ui label">نام</label>
                            <span id="id_first_name">{{ userShown.first_name }}</span>
                        </div>
                        <div class="label-seperator">
                            <label for="id_last_name" class="ui label">نام خانوادگی</label>
                            <span id="id_last_name">{{ userShown.last_name }}</span>
                        </div>
                        <div class="label-seperator">
                            <label for="id_username" class="ui label">نام کاربری</label>
                            <span dir="rtl" id="id_username">{{ userShown.username }}</span>
                        </div>
                        <div class="label-seperator">
                            <label for="id_gender" class="ui label">جنسیت</label>
                            <span id="id_gender">
                            {% if userShown.profile.gender == 'M' %}
                                مرد
                            {% else %}
                                زن
                            {% endif %}
                            </span>
                        </div>
                        <p>{% if userShown.is_staff %}
                            شما به عنوان استاد وارد شده اید
                        {% else %}
                            شما به عنوان دانشجو وارد شده اید
                        {% endif %}
                        </p>
                    </div>
                    <div class="column center aligned eight wide ">
                        <label for="id_bio" class="ui label">بیوگرافی</label>

                        <span id="id_bio">{{ userShown.profile.bio | safe }}</span>
                    </div>

                    <div class="column left aligned four wide ">
                        {% if userShown.profile.picture %}
                            <img id="id_picture" style="max-width: 200px;"
                                 src="/{{ userShown.profile.picture.url | safe }}"/>
                        {% endif %}
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <style>
        .label-seperator {
            margin-top: 10px;
            margin-bottom: 10px;
        }
    </style>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/showdown/1.9.0/showdown.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/showdown/1.9.0/showdown.js.map"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/showdown/1.9.0/showdown.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/showdown/1.9.0/showdown.min.js.map"></script>
    <script>


        function remove() {

            console.log('sga');
            var r = confirm('آیا از حذف اکانت خود اطمینان دارید؟')
            if (r == true) {
                $(location).attr('href', '/removeuser/');
            }

        }

    </script>
{% endblock %}

templates/search.html
{% extends "base.html" %}
{% block content %}
    <div class="ui right aligned center aligned grid">
        <div class="column six wide">
            {% for ostad in asatid %}
                <div class="ui card" id="id_teacher_{{ forloop.counter0 }}">
                    <div class="content">
                        <div class="header"><a name="username" href="/profile/?username={{ ostad.username }}"
                                               id="id_username">{{ ostad.username }}</a></div>
                    </div>
                    <div class="content">
                        <div class="ui small feed">
                            <div class="event">
                                <div class="content">
                                    <div class="summary">
                                        <span id="id_first_name">{{ ostad.first_name }}</span>
                                    </div>
                                </div>
                            </div>
                            <div class="event">
                                <div class="content">
                                    <div class="summary">
                                        <span id="id_last_name">{{ ostad.last_name }}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
        </div>
            {% endfor %}
             </div>

    </div>
{% endblock %}

templates/signup.html
{% extends "base.html" %}
{% block content %}
    <div class="ui middle aligned center aligned grid">
        <div class="column four wide">
            <form dir="ltr" action="." method="post" class="ui form segment">
                {% csrf_token %}
                {% if usernameExists %}
                    <p class="ui negative message">کاربری با نام کاربری وارد شده وجود دارد</p>
                {% endif %}
                {% if passNotEqual %}
                    <p class="ui negative message">گذرواژه و تکرار گذرواژه یکسان نیستند</p>
                {% endif %}
                {% if emailExists %}
                    <p class="ui negative message">کاربری با ایمیل وارد شده وجود دارد</p>
                {% endif %}
                <div class="two fields" dir="rtl">
                    <div class="field" dir="rtl">
                        <input type="text" id="id_first_name" name="first" placeholder="نام" required/>
                    </div>
                    <div class="field" dir="rtl">
                        <input type="text" id="id_last_name" name="last" placeholder="نام خانوادگی" required/>
                    </div>
                </div>
                <div class="field">
                    <div class="ui left icon input">
                        <i class="user icon"></i>
                        <input type="text" id="id_username" name="username" placeholder="نام کاربری" required/>
                    </div>
                </div>
                <div class="field">
                    <div class="ui left icon input">
                        <i class="at icon"></i>
                        <input type="email" id="id_email" name="email" placeholder="ایمیل" required/>
                    </div>
                </div>
                <div class="field">
                    <div class="ui left icon input">
                        <i class="lock icon"></i>
                        <input type="password" id="id_password1" name="pass1" placeholder="گذرواژه" required/>
                    </div>
                </div>
                <div class="field">
                    <div class="ui left icon input">
                        <i class="lock icon"></i>
                        <input type="password" id="id_password2" name="pass2" placeholder="تکرار گذرواژه" required/>
                    </div>
                </div>

                <div class="grouped fields" dir="rtl">
                    <label for="type">ثبت نام به عنوان:</label>
                    <div class="field">
                            <input type="radio" id="id_type_1" name="type" value="ostad" checked="" tabindex="0" class="hidden">
                            استاد
                    </div>
                    <div class="field">
                            <input type="radio" id="id_type_0" name="type" value="student" checked="" tabindex="0" class="hidden">
                            دانشجو
                    </div>
                </div>

                <button type="submit" id="id_submit" class="circular ui icon button green">
                    <i class=" check icon"></i>
                </button>

            </form>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    <script>
        $(document).ready(function () {
            $("#id_navbar_signup").addClass("active");
        });
        {#$('.ui.checkbox')#}
        {#    .checkbox()#}
        {#;#}
    </script>
{% endblock %}